// @ts-nocheck
/* eslint-disable */
// Generated by Specta - do not edit manually

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Fetches all active (non-archived) assets.
 */
async getAssets() : Promise<Result<Asset[], AssetApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_assets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches all assets including archived ones.
 */
async getAssetsWithArchived() : Promise<Result<Asset[], AssetApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_assets_with_archived") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a new asset.
 */
async addAsset(dto: CreateAssetDTO) : Promise<Result<Asset, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_asset", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing asset.
 */
async updateAsset(dto: UpdateAssetDTO) : Promise<Result<Asset, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_asset", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unarchives an asset (R18).
 */
async unarchiveAsset(id: string) : Promise<Result<null, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unarchive_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches all active categories.
 * 
 * Read-only — only infrastructure failures can fire here, so the surface is
 * the narrow `CategoryApplicationError` (only `DatabaseError` is reachable).
 */
async getCategories() : Promise<Result<AssetCategory[], CategoryApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new category.
 * 
 * Returns the typed `CategoryCrudError` directly — no boundary type or mapper
 * is needed because every leaf in the composite (`CategoryApplicationError`,
 * `CategoryDomainError`) already serializes with `#[serde(tag = "code")]`,
 * and `CategoryCrudError`'s `#[serde(untagged)]` flattens them into a single
 * FE-visible union.
 */
async addCategory(label: string) : Promise<Result<AssetCategory, CategoryCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_category", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing category.
 */
async updateCategory(id: string, label: string) : Promise<Result<AssetCategory, CategoryCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_category", { id, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a category.
 */
async deleteCategory(id: string) : Promise<Result<null, CategoryCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records (or overwrites) a market price for an asset on a given date (MKT-024/025).
 * price is a human-readable decimal; the backend converts to i64 micros at this boundary (MKT-024).
 */
async recordAssetPrice(assetId: string, date: string, price: number) : Promise<Result<null, AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_asset_price", { assetId, date, price }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all recorded prices for the given asset, sorted date descending (MKT-072).
 */
async getAssetPrices(assetId: string) : Promise<Result<AssetPrice[], AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_asset_prices", { assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates the date and/or price of an existing price record (MKT-083/084).
 */
async updateAssetPrice(assetId: string, originalDate: string, newDate: string, newPrice: number) : Promise<Result<null, AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_asset_price", { assetId, originalDate, newDate, newPrice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a specific price record by (asset_id, date) (MKT-090).
 */
async deleteAssetPrice(assetId: string, date: string) : Promise<Result<null, AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_asset_price", { assetId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all accounts.
 * 
 * Read-only — only infrastructure failures (DB / repository) can fire here,
 * so the surface is the narrow shared `InfrastructureError`.
 */
async getAccounts() : Promise<Result<Account[], InfrastructureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a new account.
 * 
 * Returns the typed `AccountCrudError` directly — no boundary type or mapper
 * is needed because every leaf in the composite (`AccountApplicationError`,
 * `AccountDomainError`, shared `InfrastructureError`) already serializes with
 * `#[serde(tag = "code")]`, and `AccountCrudError`'s `#[serde(untagged)]`
 * flattens them into a single FE-visible union.
 */
async addAccount(dto: CreateAccountDTO) : Promise<Result<Account, AccountCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_account", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing account.
 */
async updateAccount(dto: UpdateAccountDTO) : Promise<Result<Account, AccountCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_account", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an account.
 * 
 * Pure infrastructure surface — no domain rejections (cascade is repo-level).
 */
async deleteAccount(id: string) : Promise<Result<null, InfrastructureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the distinct asset IDs that have transactions for the given account (TXL-013).
 * 
 * Read-only — only infrastructure failures can fire here.
 */
async getAssetIdsForAccount(accountId: string) : Promise<Result<string[], InfrastructureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_asset_ids_for_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all transactions for an account/asset pair (TRX-036).
 * 
 * Read-only — only infrastructure failures (DB / repository) can fire here,
 * so the surface is a single `InfrastructureError`. The wider
 * `HoldingTransactionError` composite is reserved for write commands.
 */
async getTransactions(accountId: string, assetId: string) : Promise<Result<Transaction[], InfrastructureError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transactions", { accountId, assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Archives an asset, guarded against active holdings (OQ-6).
 */
async archiveAsset(id: string) : Promise<Result<null, ArchiveAssetError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an asset, guarded against existing transactions.
 */
async deleteAsset(id: string) : Promise<Result<null, DeleteAssetError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Seeds a holding directly from a known quantity and total cost (TRX-042, TRX-047).
 */
async openHolding(dto: OpenHoldingDTO) : Promise<Result<Transaction, OpenHoldingError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_holding", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a purchase of an asset into an account (TRX-027).
 */
async buyHolding(dto: BuyHoldingDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("buy_holding", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a sale of an asset from an account (SEL-012, SEL-021, SEL-023, SEL-024).
 */
async sellHolding(dto: SellHoldingDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sell_holding", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Corrects an existing transaction and recalculates the affected holding (TRX-031).
 */
async correctTransaction(id: string, accountId: string, dto: CorrectTransactionDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correct_transaction", { id, accountId, dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancels a transaction and recalculates (or removes) the associated holding (TRX-034).
 */
async cancelTransaction(id: string, accountId: string) : Promise<Result<null, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_transaction", { id, accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a cash deposit into an account (CSH-022).
 * 
 * The Tauri command returns the typed `HoldingTransactionError` directly — no
 * boundary type or mapper is needed because every leaf in the composite
 * (`AccountApplicationError`, `AccountOperationError`, `TransactionDomainError`,
 * shared `InfrastructureError`) already serializes with `#[serde(tag = "code")]`,
 * and `HoldingTransactionError`'s `#[serde(untagged)]` flattens them into a
 * single FE-visible union.
 */
async recordDeposit(dto: DepositDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_deposit", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a cash withdrawal from an account (CSH-032).
 */
async recordWithdrawal(dto: WithdrawalDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_withdrawal", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the full account details view for the given account (ACD-012 to ACD-041).
 */
async getAccountDetails(accountId: string) : Promise<Result<AccountDetailsResponse, AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_details", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the number of active holdings and transactions for an account (ACC-020).
 * 
 * Used by the frontend to decide whether to show the standard or reinforced
 * delete confirmation dialog (ACC-018 vs ACC-019).
 */
async getAccountDeletionSummary(accountId: string) : Promise<Result<AccountDeletionSummary, AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_deletion_summary", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Searches OpenFIGI for instruments matching the query and returns up to 10
 * results (WEB-020, WEB-022).
 * 
 * Routing is transparent to the caller: 12-char alphanumeric queries are sent
 * to the ISIN mapping endpoint; all others to the keyword search endpoint
 * (WEB-014). Network or HTTP failures surface as
 * `WebLookupApplicationError::NetworkError` (WEB-025).
 */
async lookupAsset(query: string) : Promise<Result<AssetLookupResult[], WebLookupApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lookup_asset", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks whether a new application version is available (R1, R25).
 * 
 * Returns `None` if the application is up to date or if the check fails due
 * to network or server errors (R21). Emits `"update:available"` on the app
 * handle if an update is found.
 */
async checkForUpdate() : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts downloading the available update in the background (R6).
 * 
 * Returns immediately — the download runs as a detached async task.
 * Progress is reported via `"update:progress"` events (R8).
 * On success, emits `"update:complete"` (R11).
 * On failure, emits `"update:error"` (R23).
 * Concurrent download requests are silently ignored (R10).
 */
async downloadUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Installs the downloaded update and restarts the application (R13).
 * 
 * Must be called after `download_update` has completed successfully.
 * Returns an error if no downloaded update is available.
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command allowing the frontend to emit structured log entries
 * into the backend tracing system (visible in app logs and collect-logs output).
 */
async logFrontend(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("log_frontend", { level, message });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
event: Event
}>({
event: "event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Represents a financial account — the Aggregate Root of the Account bounded context.
 * Owns all holdings and transactions for this account.
 * 
 * The `holdings`, `transactions`, and `pending_changes` fields are populated only
 * when the aggregate is loaded for mutation via `AccountRepository::get_with_holdings_and_transactions`.
 * They are excluded from Tauri serialization and TypeScript bindings.
 */
export type Account = { 
/**
 * Unique identifier (uuid).
 */
id: string; 
/**
 * User defined name.
 */
name: string; 
/**
 * ISO 4217 currency code for this account (TRX-021).
 */
currency: string; 
/**
 * How often this account is updated.
 */
update_frequency: UpdateFrequency }
/**
 * Application-layer errors raised by the Account bounded context — concerns
 * that belong to use-case orchestration rather than aggregate invariants.
 * 
 * Per Rule B' (`docs/plan/error-model-refactor.md`): an error is **domain**
 * only if raised by an aggregate method on its own loaded state. Anything
 * raised at the service/use-case layer — `NotFound` lookups, cross-aggregate
 * preconditions, infrastructure translations — is **application**.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "...", ... }` shape, identical to
 * existing domain error enums.
 */
export type AccountApplicationError = 
/**
 * No account exists with the requested ID. Born at the service layer
 * when a repository lookup returns `None`; never raised by an aggregate.
 * `account_id` mirrors the (deprecated) `AccountDomainError::AccountNotFound`
 * payload so the diagnostic chain doesn't lose the requested ID.
 */
{ code: "AccountNotFound"; account_id: string } | 
/**
 * Account name (case-insensitive) collides with an existing one. Born at
 * the service layer from a `find_by_name` uniqueness pre-check before the
 * repository write — a cross-aggregate invariant, not a single-aggregate
 * state rule, so application-class per Rule B'.
 */
{ code: "NameAlreadyExists" } | 
/**
 * Application-layer translation of any infrastructure failure from an
 * account-side repository call. Unit variant — no `hint` payload on the
 * wire; the full diagnostic chain is preserved server-side via
 * `tracing::error!` at the translation site. FE shows the i18n key
 * `error.DatabaseError`. Per the project-specific infra-translation rule
 * (`docs/plan/error-model-refactor.md`).
 */
{ code: "DatabaseError" }
/**
 * Service-layer composite for the **Account CRUD** failure surface — the
 * write commands `add_account` and `update_account`. Replaces the anyhow-era
 * `AccountCommandError` boundary type per the rejection-layer rule
 * (`docs/ddd-reference.md` § Errors): each leaf retains its single, typed
 * failure source in its proper layer; `#[serde(untagged)]` flattens them
 * into a single FE-visible union of `{ code: "..." }` discriminated variants.
 * 
 * **This IS the FE-facing contract** for `add_account` / `update_account`.
 * No separate boundary type / mapper is needed. `delete_account`,
 * `get_accounts`, and `get_asset_ids_for_account` use the narrower shared
 * `InfrastructureError` directly because they have no domain-rejection paths.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer (this module) — raises
 * `NameAlreadyExists` from the service-layer uniqueness pre-check.
 * - `AccountDomainError` — domain layer (`account/domain/`) — raises
 * `NameEmpty` / `InvalidCurrency` from the `Account::new` /
 * `Account::with_id` constructors on their own input.
 * - `InfrastructureError` — shared catch-all (`core/`) — opaques repository
 * failures.
 * 
 * `AccountCrudError` itself owns no variants; it only enumerates which
 * leaves the create/update commands can produce.
 */
export type AccountCrudError = 
/**
 * Service-layer rejection (`NameAlreadyExists`).
 */
AccountApplicationError | 
/**
 * Aggregate-constructor rejection (`NameEmpty`, `InvalidCurrency`).
 */
AccountDomainError | 
/**
 * Opaque catch-all for repository failures.
 */
InfrastructureError
/**
 * Pre-deletion counts for an account (ACC-020).
 */
export type AccountDeletionSummary = { 
/**
 * Number of active holdings (quantity > 0) in the account.
 */
holding_count: number; 
/**
 * Total number of transactions associated with the account.
 */
transaction_count: number }
/**
 * Top-level response for the get_account_details command (ACD spec).
 */
export type AccountDetailsResponse = { 
/**
 * Display name of the account (ACD-032).
 */
account_name: string; 
/**
 * Active holdings (quantity > 0), sorted by asset_name asc (ACD-020, ACD-033).
 */
holdings: HoldingDetail[]; 
/**
 * Closed positions (quantity == 0), sorted by asset_name asc (ACD-044, ACD-046).
 */
closed_holdings: ClosedHoldingDetail[]; 
/**
 * Total holding count regardless of quantity (ACD-034).
 */
total_holding_count: number; 
/**
 * Sum of cost_basis across all active holdings, 0 if none (ACD-031).
 */
total_cost_basis: number; 
/**
 * Sum of total_realized_pnl across ALL holdings (active + closed), 0 if none (ACD-047).
 */
total_realized_pnl: number; 
/**
 * Sum of unrealized_pnl across same-currency priced active holdings. None when none qualify (MKT-040).
 */
total_unrealized_pnl: number | null; 
/**
 * Total economic value of the account in account-currency micros (CSH-094):
 * `cash_holding.quantity + Σ_h (h.quantity × latest_price(h))` over non-cash active holdings.
 * Unpriced non-cash holdings contribute 0 (no fallback to `average_price`).
 * Returns 0 when no Cash Holding and no priced non-cash holdings.
 */
total_global_value: number }
/**
 * Typed errors for the account bounded context.
 * 
 * All domain error enums in this module derive `serde::Serialize` + `specta::Type` +
 * `#[serde(tag = "code")]` so they can be exposed verbatim at the Tauri boundary.
 * Boundary error types compose them via untagged unions to avoid redefining variants
 * (review feedback on PR #5).
 */
export type AccountDomainError = 
/**
 * Account name is empty or whitespace-only. Raised by the `Account`
 * aggregate constructor on its own input — value-object validation,
 * domain-class per Rule B'.
 */
{ code: "NameEmpty" } | 
/**
 * The currency string is not a valid ISO 4217 code. Raised by the
 * `Account` aggregate constructor on its own input. Struct variant so the
 * internally-tagged serde representation (`#[serde(tag = "code")]`) can
 * flatten the offending currency alongside `code` at the FE boundary
 * (serde does not support internally-tagged tuple variants).
 */
{ code: "InvalidCurrency"; currency: string }
/**
 * Typed errors raised by Account aggregate operations (buy/sell/correct/cancel/cash).
 */
export type AccountOperationError = 
/**
 * Attempt to sell an asset with no open position (quantity = 0).
 */
{ code: "ClosedPosition" } | 
/**
 * Sell quantity exceeds the currently held units.
 */
{ code: "Oversell"; available: number; requested: number } | 
/**
 * Correcting a transaction would leave a later sell with insufficient units.
 */
{ code: "CascadingOversell" } | 
/**
 * No transaction with the given ID exists within this account.
 */
{ code: "TransactionNotFound" } | 
/**
 * Attempted cash debit (or chronological replay step) would drive the cash holding strictly negative (CSH-080).
 */
{ code: "InsufficientCash"; current_balance_micros: number; currency: string }
/**
 * Application-layer rejection specific to the `archive_asset` use case —
 * the cross-BC active-holdings check performed by the orchestrator before
 * delegating to `AssetService::archive_asset`.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors): this
 * rejection is born at the orchestrator (it queries the account service and
 * decides whether to proceed), not by an aggregate method on its own loaded
 * state — application-class.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape through the
 * `ArchiveAssetError` untagged composite.
 */
export type ArchiveAssetApplicationError = 
/**
 * Asset still has non-zero holdings in at least one account (OQ-6).
 */
{ code: "ActiveHoldings" }
/**
 * Use-case composite for the **archive asset** failure surface — the single
 * command `archive_asset` (OQ-6) and its full chain of rejections.
 * 
 * Replaces the anyhow-era `ArchiveAssetCommandError` boundary type. This IS
 * the FE-facing contract for the `archive_asset` Tauri command — each leaf
 * already serializes with `#[serde(tag = "code")]`, and `#[serde(untagged)]`
 * here flattens them into a single FE-visible union.
 * 
 * Each leaf lives in its rightful layer:
 * - `AssetCrudError` — asset BC composite (`asset/application/`), carries
 * `AssetApplicationError::NotFound` and
 * `AssetDomainError::CashAssetNotEditable` propagated verbatim per the
 * composition-over-redefinition rule.
 * - `AccountApplicationError` — account BC (`account/application/`), surfaces
 * `DatabaseError` from the cross-BC active-holdings check.
 * - `ArchiveAssetApplicationError` — use-case-owned (this file), raises
 * `ActiveHoldings` from the orchestrator.
 */
export type ArchiveAssetError = 
/**
 * Asset BC rejection (`NotFound`, `CashAssetNotEditable`, propagated
 * `DatabaseError`).
 */
AssetCrudError | 
/**
 * Account BC rejection (`DatabaseError` from the cross-BC
 * active-holdings check).
 */
AccountApplicationError | 
/**
 * Use-case orchestration rejection (`ActiveHoldings`).
 */
ArchiveAssetApplicationError
/**
 * A financial instrument or resource held by a user.
 */
export type Asset = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * Display name.
 */
name: string; 
/**
 * Asset classification.
 */
class: AssetClass; 
/**
 * Category link.
 */
category: AssetCategory; 
/**
 * ISO 4217 currency code.
 */
currency: string; 
/**
 * Risk score from 1 to 5.
 */
risk_level: number; 
/**
 * Identifier like ticker or ISIN.
 */
reference: string; 
/**
 * Whether the asset is archived (soft-archived, reversible).
 */
is_archived: boolean }
/**
 * Application-layer rejections for the Asset aggregate of the Asset BC —
 * concerns raised at the service layer rather than by an aggregate method on
 * its own loaded state.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `NotFound` is born when `asset_repo.get_by_id` returns `Ok(None)` — a
 * service-level translation, not an aggregate invariant. Carries the
 * requested ID for FE diagnostic surfacing.
 * - `DatabaseError` is the application-layer translation of any raw
 * infrastructure failure from an asset-repo call. The diagnostic chain is
 * preserved via `tracing::error!` at the same translation site; the
 * variant carries no payload (per the project-specific infra-translation
 * rule in `docs/plan/error-model-refactor.md`).
 */
export type AssetApplicationError = 
/**
 * No asset exists with the requested ID. Born at the service layer when
 * `asset_repo.get_by_id` returns `None`.
 */
{ code: "NotFound"; id: string } | 
/**
 * Application-layer translation of any infrastructure failure from an
 * asset-repo call. Unit variant — no `hint` payload on the wire; the full
 * diagnostic chain is preserved server-side via `tracing::error!` at the
 * translation site. FE shows the i18n key `error.DatabaseError`.
 */
{ code: "DatabaseError" }
/**
 * A user-defined grouping for assets.
 */
export type AssetCategory = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * Display name.
 */
name: string }
/**
 * Represents the classification of an asset.
 */
export type AssetClass = 
/**
 * Real estate properties or REITs.
 */
"RealEstate" | 
/**
 * Fiat currency or highly liquid equivalents.
 */
"Cash" | 
/**
 * Individual company equities.
 */
"Stocks" | 
/**
 * Fixed income securities.
 */
"Bonds" | 
/**
 * Exchange Traded Funds.
 */
"ETF" | 
/**
 * Managed investment funds.
 */
"MutualFunds" | 
/**
 * Cryptocurrencies or other blockchain-based assets.
 */
"DigitalAsset" | 
/**
 * Leveraged or contingent instruments derived from an underlying asset (warrants, options, futures, rights).
 */
"Derivatives"
/**
 * Service-layer composite for the Asset CRUD failure surface — the write
 * commands `add_asset`, `update_asset`, `unarchive_asset`, plus the
 * service-internal `archive_asset` / `delete_asset` consumed by use cases.
 * 
 * Composes three leaves: `AssetApplicationError` (NotFound, DatabaseError),
 * `AssetDomainError` (input validation + archive / cash / system-managed
 * invariants), `CategoryApplicationError` (cross-aggregate category lookup
 * in create/update). No `Infrastructure` leaf — infra failures translate at
 * the application layer into `AssetApplicationError::DatabaseError` per the
 * project's infra-translation rule (`docs/plan/error-model-refactor.md`).
 */
export type AssetCrudError = 
/**
 * Service-layer rejection (`NotFound`, `DatabaseError`).
 */
AssetApplicationError | 
/**
 * Aggregate-level domain rejection (input validation, archive / cash /
 * system-managed invariants on loaded state).
 */
AssetDomainError | 
/**
 * Category-side application rejection — surfaces `NotFound { id }` from the
 * cross-aggregate category lookup in `create_asset` / `update_asset`.
 */
CategoryApplicationError
/**
 * Typed errors for asset domain validation. Only aggregate-method or
 * value-object rejections live here per the rejection-layer rule
 * (`docs/ddd-reference.md` § Errors).
 * 
 * Tagged with `#[serde(tag = "code")]` for exposure through the
 * `AssetCrudError` untagged composite. Payload-bearing variants are
 * struct-shaped (internally-tagged serde rejects tuple variants).
 */
export type AssetDomainError = 
/**
 * Asset name is empty or whitespace-only.
 */
{ code: "NameEmpty" } | 
/**
 * Asset reference (ticker/ISIN) is empty or whitespace-only.
 */
{ code: "ReferenceEmpty" } | 
/**
 * Risk level is outside the 1–5 range.
 */
{ code: "InvalidRiskLevel"; received: number } | 
/**
 * The currency string is not a valid ISO 4217 code.
 */
{ code: "InvalidCurrency"; currency: string } | 
/**
 * The asset is archived and cannot be edited.
 */
{ code: "Archived" } | 
/**
 * The asset is a system Cash Asset and cannot be edited, archived, unarchived, or deleted (CSH-016).
 */
{ code: "CashAssetNotEditable" }
/**
 * Transient value object returned by the orchestrator's `search` method.
 * Mirrors the shape exposed at the Tauri boundary.
 */
export type AssetLookupResult = { 
/**
 * Full instrument name (e.g. `"AIR LIQUIDE SA"`).
 */
name: string; 
/**
 * ISIN (ISIN path) or ticker (keyword path); `None` when no value is
 * available (WEB-046).
 */
reference: string | null; 
/**
 * ISO 4217 currency forwarded from OpenFIGI (WEB-024).
 */
currency: string | null; 
/**
 * Asset class derived from `securityType` (WEB-023).
 */
asset_class: AssetClass | null; 
/**
 * Human-readable exchange name resolved from `exchCode` (WEB-049).
 */
exchange: string | null }
/**
 * A manually recorded market price for a financial asset on a specific date.
 * Owned by the `asset` bounded context (MKT spec).
 */
export type AssetPrice = { 
/**
 * ID of the asset whose market price this record describes.
 */
asset_id: string; 
/**
 * ISO 8601 calendar date of the price observation (e.g. "2026-04-26").
 */
date: string; 
/**
 * Market price per unit in the asset's native currency (i64 micro-units, ADR-001).
 */
price: number }
/**
 * Application-layer rejections for the AssetPrice sub-aggregate of the Asset
 * BC — concerns raised at the service layer rather than by an aggregate method
 * on its own loaded state.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `PriceNotFound` is born when `price_repo.get_by_asset_and_date` returns
 * `Ok(None)` for an `(asset_id, date)` pair the service expected to exist
 * (update / delete) — a service-level translation, not an aggregate
 * invariant. Carries both keys for FE diagnostic surfacing.
 * - `DatabaseError` is the application-layer translation of any raw infra
 * failure from a price-repo call. The diagnostic chain is preserved via
 * `tracing::error!` at the same translation site; the variant carries no
 * payload (per the project-specific infra-translation rule in
 * `docs/plan/error-model-refactor.md`).
 */
export type AssetPriceApplicationError = 
/**
 * No price record exists for the given (asset_id, date) pair (MKT-083 / MKT-090).
 */
{ code: "PriceNotFound"; asset_id: string; date: string } | 
/**
 * Application-layer translation of any infrastructure failure from a
 * price-repo call. Unit variant — no `hint` payload on the wire; the full
 * diagnostic chain is preserved server-side via `tracing::error!` at the
 * translation site. FE shows the i18n key `error.DatabaseError`.
 */
{ code: "DatabaseError" }
/**
 * Typed errors for asset price value-object validation. Only aggregate-method
 * or value-object rejections live here per the rejection-layer rule
 * (`docs/ddd-reference.md` § Errors); the "no record at this (asset_id, date)"
 * rejection is service-level and lives in `AssetPriceApplicationError`.
 * 
 * Tagged with `#[serde(tag = "code")]` for exposure through the
 * `AssetPriceError` untagged composite. Payload-bearing variants are
 * struct-shaped (internally-tagged serde rejects tuple variants).
 */
export type AssetPriceDomainError = 
/**
 * Price must be strictly positive.
 */
{ code: "NotPositive" } | 
/**
 * Price value is not a finite floating-point number.
 * Emitted by the service boundary before micro conversion; `AssetPrice::new()` never produces this.
 */
{ code: "NonFinite" } | 
/**
 * Price date is in the future.
 */
{ code: "DateInFuture" } | 
/**
 * The supplied date string is not parseable as ISO 8601 (`YYYY-MM-DD`).
 */
{ code: "InvalidDateFormat"; date: string }
/**
 * Service-layer composite for the **AssetPrice** failure surface — the write
 * commands `record_asset_price` / `update_asset_price` / `delete_asset_price`
 * and the read `get_asset_prices`.
 * 
 * Replaces the anyhow-era trio of boundary types
 * (`AssetPriceCommandError`, `UpdateAssetPriceCommandError`,
 * `DeleteAssetPriceCommandError`) with a single composite per the
 * family-map (`docs/plan/error-model-refactor.md` § Failure-surface-family map
 * → Asset price row). Continues the gold infra-translation rule (no shared
 * `InfrastructureError` leaf — translated to per-BC `*ApplicationError::DatabaseError`).
 * 
 * Composes three leaves:
 * - `AssetApplicationError` — cross-aggregate asset-existence check
 * (`record_asset_price` and `get_asset_prices` reject when the asset row
 * itself is missing — MKT-043).
 * - `AssetPriceApplicationError` — price-row rejection (`PriceNotFound`,
 * `DatabaseError`).
 * - `AssetPriceDomainError` — value-object validation
 * (`NotPositive` / `NonFinite` / `DateInFuture` / `InvalidDateFormat`).
 */
export type AssetPriceError = 
/**
 * Asset-row rejection (`NotFound`, `DatabaseError`) from the
 * asset-existence check that gates write commands.
 */
AssetApplicationError | 
/**
 * Price-row rejection (`PriceNotFound`, `DatabaseError`).
 */
AssetPriceApplicationError | 
/**
 * Value-object validation (`NotPositive`, `NonFinite`, `DateInFuture`,
 * `InvalidDateFormat`).
 */
AssetPriceDomainError
/**
 * Parameters for recording a purchase of an asset into an account.
 */
export type BuyHoldingDTO = { 
/**
 * Account where the purchase is recorded.
 */
account_id: string; 
/**
 * Financial asset being purchased.
 */
asset_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Quantity in micro-units.
 */
quantity: number; 
/**
 * Unit price in asset currency (micro-units).
 */
unit_price: number; 
/**
 * Exchange rate asset→account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Fees in account currency (micro-units).
 */
fees: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Application-layer rejections for the Category sub-aggregate of the Asset
 * bounded context — concerns raised at the service layer rather than by an
 * aggregate method on its own loaded state.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `NotFound` is born when `category_repo.get_by_id` returns `Ok(None)` —
 * a service-level translation, not an aggregate invariant.
 * - `DuplicateName` is born when the service-layer `find_by_name` uniqueness
 * pre-check matches an existing row — a cross-aggregate invariant.
 * - `DatabaseError` is the application-layer translation of any raw
 * infrastructure failure from a category-repo call. The diagnostic chain
 * is preserved via `tracing::error!` at the same translation site; the
 * variant carries no payload (per the project-specific infra-translation
 * rule in `docs/plan/error-model-refactor.md`).
 * 
 * Tagged with `#[serde(tag = "code")]` so each variant serializes as a flat
 * `{ code: "..." }` shape across the Tauri boundary. `NotFound` carries the
 * requested ID as a struct field so the FE can surface it diagnostically.
 */
export type CategoryApplicationError = 
/**
 * No category exists with the requested ID. Born at the service layer
 * when `category_repo.get_by_id` returns `None`.
 */
{ code: "NotFound"; id: string } | 
/**
 * A category with the same name (case-insensitive) already exists. Born
 * at the service layer from a `find_by_name` uniqueness pre-check before
 * the repository write — a cross-aggregate invariant, not a single-
 * aggregate state rule.
 */
{ code: "DuplicateName" } | 
/**
 * Application-layer translation of any infrastructure failure from a
 * category-repo call. Unit variant — no `hint` payload on the wire; the
 * full diagnostic chain is preserved server-side via `tracing::error!`
 * at the translation site. FE shows the i18n key `error.DatabaseError`.
 */
{ code: "DatabaseError" }
/**
 * Service-layer composite for the **Category CRUD** failure surface — the
 * write commands `add_category`, `update_category`, `delete_category`.
 * 
 * Replaces the anyhow-era `CategoryCommandError` boundary type. **First PR
 * (6) enforcing the gold infra-translation rule**: this composite has NO
 * shared `InfrastructureError` leaf — infra failures are translated at the
 * application layer into `CategoryApplicationError::DatabaseError` (typed,
 * payload-free) rather than passed through opaquely.
 * 
 * **This IS the FE-facing contract** for write commands. `get_categories`
 * (read-only) returns the narrower `CategoryApplicationError` directly
 * because it has no domain-rejection paths.
 * 
 * Each leaf lives in its rightful layer:
 * - `CategoryApplicationError` — application layer (this module) — raises
 * `NotFound`, `DuplicateName`, `DatabaseError`.
 * - `CategoryDomainError` — domain layer (`asset/domain/`) — raises
 * `LabelEmpty` (value-object validation), `SystemReadonly` /
 * `SystemProtected` (aggregate-method invariants on loaded state).
 * 
 * `CategoryCrudError` itself owns no variants; it only enumerates which
 * leaves the create/update/delete commands can produce.
 */
export type CategoryCrudError = 
/**
 * Service-layer rejection (`NotFound`, `DuplicateName`, `DatabaseError`).
 */
CategoryApplicationError | 
/**
 * Aggregate-level domain rejection (`LabelEmpty`, `SystemReadonly`,
 * `SystemProtected`).
 */
CategoryDomainError
/**
 * Typed errors for category domain validation.
 * 
 * Only genuine aggregate-method or value-object rejections live here per the
 * rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `LabelEmpty` — value-object validation in `AssetCategory::new` /
 * `update_from`.
 * - `SystemReadonly` / `SystemProtected` — aggregate methods
 * `ensure_renameable` / `ensure_deletable` enforced on loaded state.
 * 
 * Tagged with `#[serde(tag = "code")]` so it can be exposed verbatim at the
 * Tauri boundary through the `CategoryCrudError` untagged composite.
 */
export type CategoryDomainError = 
/**
 * Category label is empty or whitespace-only.
 */
{ code: "LabelEmpty" } | 
/**
 * Attempt to rename the system default category.
 */
{ code: "SystemReadonly" } | 
/**
 * Attempt to delete the system default category.
 */
{ code: "SystemProtected" }
/**
 * Enriched view of a fully-closed position (quantity == 0, ACD-044).
 */
export type ClosedHoldingDetail = { 
/**
 * ID of the previously held asset.
 */
asset_id: string; 
/**
 * Display name of the asset.
 */
asset_name: string; 
/**
 * Ticker or user-defined reference.
 */
asset_reference: string; 
/**
 * Total realized P&L for this position (micro-units, ACD-045).
 */
realized_pnl: number; 
/**
 * ISO date of the most recent sell for this position ("YYYY-MM-DD", ACD-043).
 */
last_sold_date: string }
/**
 * Parameters for correcting an existing transaction.
 * `account_id` and `asset_id` are immutable — taken from the existing transaction.
 */
export type CorrectTransactionDTO = { 
/**
 * Corrected transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Corrected quantity in micro-units.
 */
quantity: number; 
/**
 * Corrected unit price in asset currency (micro-units).
 */
unit_price: number; 
/**
 * Corrected exchange rate asset→account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Corrected fees in account currency (micro-units).
 */
fees: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Parameters for creating a new account.
 */
export type CreateAccountDTO = { 
/**
 * Display name.
 */
name: string; 
/**
 * ISO 4217 currency code.
 */
currency: string; 
/**
 * Update frequency.
 */
update_frequency: UpdateFrequency }
/**
 * Parameters for creating a new asset.
 */
export type CreateAssetDTO = { 
/**
 * Display name.
 */
name: string; 
/**
 * Ticker, ISIN, or user-defined reference (mandatory — R1).
 */
reference: string; 
/**
 * Classification type.
 */
class: AssetClass; 
/**
 * ISO currency code.
 */
currency: string; 
/**
 * 1-5 risk score.
 */
risk_level: number; 
/**
 * ID of the primary category.
 */
category_id: string }
/**
 * Application-layer rejection specific to the `delete_asset` use case —
 * the cross-BC transaction-history check performed by the orchestrator
 * before delegating to `AssetService::delete_asset`.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors): this
 * rejection is born at the orchestrator (it queries the account service and
 * decides whether to proceed), not by an aggregate method on its own loaded
 * state — application-class.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape through the
 * `DeleteAssetError` untagged composite.
 */
export type DeleteAssetApplicationError = 
/**
 * At least one transaction references this asset; deletion would break history.
 */
{ code: "ExistingTransactions" }
/**
 * Use-case composite for the **delete asset** failure surface — the single
 * command `delete_asset` and its full chain of rejections.
 * 
 * Replaces the anyhow-era `DeleteAssetCommandError` boundary type. This IS
 * the FE-facing contract for the `delete_asset` Tauri command — each leaf
 * already serializes with `#[serde(tag = "code")]`, and `#[serde(untagged)]`
 * here flattens them into a single FE-visible union.
 * 
 * Each leaf lives in its rightful layer:
 * - `AssetCrudError` — asset BC composite (`asset/application/`), carries
 * `AssetApplicationError::NotFound` and
 * `AssetDomainError::CashAssetNotEditable` propagated verbatim per the
 * composition-over-redefinition rule.
 * - `AccountApplicationError` — account BC (`account/application/`), surfaces
 * `DatabaseError` from the cross-BC transaction-history check.
 * - `DeleteAssetApplicationError` — use-case-owned (this file), raises
 * `ExistingTransactions` from the orchestrator.
 */
export type DeleteAssetError = 
/**
 * Asset BC rejection (`NotFound`, `CashAssetNotEditable`, propagated
 * `DatabaseError`).
 */
AssetCrudError | 
/**
 * Account BC rejection (`DatabaseError` from the cross-BC
 * transaction-history check).
 */
AccountApplicationError | 
/**
 * Use-case orchestration rejection (`ExistingTransactions`).
 */
DeleteAssetApplicationError
/**
 * Parameters for recording a cash deposit (CSH-020).
 */
export type DepositDTO = { 
/**
 * Account receiving the cash.
 */
account_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Deposited amount in account currency (micro-units); strictly positive (CSH-021).
 */
amount_micros: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * All possible side-effect events that can be published across the application.
 * Each variant represents a specific business event that features may need to react to.
 */
export type Event = 
/**
 * Health check event for testing/monitoring
 */
{ type: "Health" } | 
/**
 * An asset was created, updated, or deleted
 */
{ type: "AssetUpdated" } | 
/**
 * An account was created, updated, or deleted
 */
{ type: "AccountUpdated" } | 
/**
 * A category was created, updated, or deleted
 */
{ type: "CategoryUpdated" } | 
/**
 * A transaction was created, updated, or deleted (position data changed)
 */
{ type: "TransactionUpdated" } | 
/**
 * A market price was recorded or updated for an asset (MKT-026)
 */
{ type: "AssetPriceUpdated" }
/**
 * Current state of a financial position: an asset held within an account (ADR-002).
 * All financial fields are stored as i64 micro-units (ADR-001).
 */
export type Holding = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * The account holding the asset.
 */
account_id: string; 
/**
 * The financial asset held.
 */
asset_id: string; 
/**
 * Current number of units held (micro-units: value × 10^6).
 */
quantity: number; 
/**
 * Volume-weighted average purchase price in account currency (micro-units).
 */
average_price: number; 
/**
 * Cumulative realized P&L from all sell transactions (micro-units, ACD-045).
 */
total_realized_pnl: number; 
/**
 * ISO date of the most recent sell transaction, if any (ACD-043).
 */
last_sold_date: string | null }
/**
 * Enriched view of a single active holding (quantity > 0) with asset metadata (ACD-020).
 */
export type HoldingDetail = { 
/**
 * ID of the held asset.
 */
asset_id: string; 
/**
 * Display name of the asset.
 */
asset_name: string; 
/**
 * Ticker or user-defined reference.
 */
asset_reference: string; 
/**
 * Current units held (i64 micro-units, ADR-001).
 */
quantity: number; 
/**
 * VWAP purchase price in account currency (i64 micro-units, ADR-001).
 */
average_price: number; 
/**
 * Total cost of position: quantity × average_price / MICRO (i64 micro-units, ACD-023).
 */
cost_basis: number; 
/**
 * Sum of realized P&L from all Sell transactions for this asset (i64 micro-units, SEL-042).
 */
realized_pnl: number; 
/**
 * ISO 4217 currency code of the asset's native currency (MKT-023).
 */
asset_currency: string; 
/**
 * Most recently dated price for this asset in asset currency (i64 micros). None if no price recorded (MKT-031).
 */
current_price: number | null; 
/**
 * ISO date string of the price observation. None when current_price is None (MKT-031).
 */
current_price_date: string | null; 
/**
 * Unrealized gain/loss in account currency (i64 micros). None on currency mismatch or no price (MKT-033/034).
 * 0 (not None) when current price equals average price (MKT-033).
 */
unrealized_pnl: number | null; 
/**
 * Performance percentage as i64 micros (5.25% = 5_250_000). None when unrealized_pnl is None or cost_basis = 0 (MKT-035).
 * 0 (not None) when unrealized_pnl is 0 (MKT-035).
 */
performance_pct: number | null }
/**
 * Service-layer composite for the **holding-transaction** failure surface —
 * every operation that mutates an Account's holdings ledger:
 * `record_deposit`, `record_withdrawal`, `buy_holding`, `sell_holding`,
 * `correct_transaction`, `cancel_transaction`.
 * 
 * Cash deposit / withdrawal are the special case where the holding IS the
 * System Cash Asset (CSH-014); mechanically they share the same aggregate,
 * the same replay invariants, and therefore the same failure surface. So
 * they share the composite — one FE-facing type covers all six commands.
 * 
 * Replaces the deleted domain-layer `CashOperationError` and the anyhow-era
 * `TransactionCommandError` boundary type per Rule B' — composition belongs
 * in the application layer; each leaf retains its single, typed failure
 * source in its proper layer.
 * 
 * **This IS the FE-facing contract** for holding-transaction Tauri commands.
 * No separate boundary type / mapper is needed: the four leaf enums below
 * each derive `Serialize` + `specta::Type` with `#[serde(tag = "code")]`, and
 * `#[serde(untagged)]` here flattens them into a single FE-visible union of
 * `{ code: "...", ... }` discriminated variants.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer (`account/application/`)
 * - `AccountOperationError` — domain layer (`account/domain/`)
 * - `TransactionDomainError` — domain layer (`account/domain/`)
 * - `InfrastructureError` — shared catch-all (`core/`)
 * 
 * `HoldingTransactionError` itself owns no variants; it only enumerates which
 * leaves any holding-transaction command can produce.
 */
export type HoldingTransactionError = 
/**
 * Application-layer rejection (`AccountNotFound`).
 */
AccountApplicationError | 
/**
 * Aggregate-level domain rejection (e.g. `InsufficientCash` from
 * `Account::apply_withdrawal`, `Oversell` from `sell_holding`).
 */
AccountOperationError | 
/**
 * Transaction-factory validation rejection (invalid date, negative
 * quantity, `AmountNotPositive` from cash factories, etc.).
 */
TransactionDomainError | 
/**
 * Opaque catch-all for repository / cross-BC infrastructure failures.
 * Wire shape: `{ code: "Unknown", hint: "..." }`. The `hint` mirrors the
 * corresponding `tracing::error!` log; FE shows `error.Unknown`.
 */
InfrastructureError
/**
 * Shared application-wide infrastructure-error type.
 * 
 * Composed into every typed service composite (e.g. `HoldingTransactionError`)
 * via `#[from]` so any layer can translate an opaque infrastructure failure
 * (repository crash, file-system error, network failure, deserialization
 * error, cross-BC infra step) into a typed leaf without re-defining the same
 * `Unknown { hint }` shape per bounded context.
 * 
 * Per `docs/ddd-reference.md` § Errors travel rule: raw infrastructure
 * failures must be translated at the application boundary into either a
 * meaningful application error OR an opaque variant. This is the latter —
 * the `hint` is developer-only diagnostic mirroring the corresponding
 * `tracing::error!` log; the FE displays the i18n key `error.Unknown` and
 * forwards `hint` to the JS console via `logger.error`.
 * 
 * Tagged with `#[serde(tag = "code")]` so the wire shape is
 * `{ code: "Unknown", hint: "..." }` — identical across every command that
 * surfaces it through any composite.
 */
export type InfrastructureError = 
/**
 * Opaque catch-all for any infrastructure failure with no domain meaning.
 * Construct via `InfrastructureError::Unknown { hint: format!("...") }`
 * or via `?` from any composite that has `#[from] InfrastructureError`.
 */
{ code: "Unknown"; hint: string }
/**
 * Application-layer rejections specific to the `open_holding` use case —
 * cross-BC asset checks performed by the orchestrator before delegating to
 * `AccountService::open_holding`.
 * 
 * Per Rule B' (`docs/plan/error-model-refactor.md`): an error is **domain**
 * only if raised by an aggregate method on its own loaded state. These three
 * rejections are use-case orchestration concerns (the orchestrator queries
 * the asset service and decides whether to proceed) — application-class.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape.
 */
export type OpenHoldingApplicationError = 
/**
 * No asset exists with the requested ID (TRX-056).
 */
{ code: "AssetNotFound" } | 
/**
 * Target asset is archived — cannot open a holding (TRX-050).
 * The orchestrator does not auto-unarchive; the caller must unarchive
 * explicitly through the asset BC first.
 */
{ code: "ArchivedAsset" } | 
/**
 * Target asset is a system Cash Asset (CSH-061). Initial cash should be
 * recorded via `record_deposit`, which goes through the cash-recording
 * path and lazy-creates the Cash Holding.
 */
{ code: "OpeningBalanceOnCashAsset" }
/**
 * Parameters for recording an opening balance for an asset in an account (TRX-042).
 */
export type OpenHoldingDTO = { 
/**
 * Account where the opening balance is recorded.
 */
account_id: string; 
/**
 * Financial asset being seeded.
 */
asset_id: string; 
/**
 * Date of the opening balance (YYYY-MM-DD).
 */
date: string; 
/**
 * Quantity in micro-units; strictly positive (TRX-044).
 */
quantity: number; 
/**
 * Total cost paid in account currency (micro-units); strictly positive (TRX-045).
 */
total_cost: number }
/**
 * Use-case composite for the **open holding** failure surface — the single
 * command `open_holding` (TRX-042) and its full chain of rejections. Replaces
 * the anyhow-era `OpenHoldingCommandError` boundary type per Rule B' —
 * composition belongs in the use-case layer; each leaf retains its single,
 * typed failure source in its proper layer.
 * 
 * **This IS the FE-facing contract** for the `open_holding` Tauri command.
 * No separate boundary type / mapper is needed: each leaf below derives
 * `Serialize` + `specta::Type` with `#[serde(tag = "code")]`, and
 * `#[serde(untagged)]` here flattens them into a single FE-visible union of
 * `{ code: "...", ... }` discriminated variants.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer (`account/application/`),
 * raises `AccountNotFound { account_id }` from the service-layer load.
 * - `OpenHoldingApplicationError` — use-case-owned (this file), raises the
 * 3 cross-BC rejections (`AssetNotFound`, `ArchivedAsset`,
 * `OpeningBalanceOnCashAsset`).
 * - `OpeningBalanceDomainError` — domain layer (`account/domain/`), raises
 * `InvalidTotalCost` from `Account::open_holding` on its own input.
 * - `TransactionDomainError` — domain layer (`account/domain/`), raises
 * the date / quantity invariants enforced by `Transaction::new`.
 * - `InfrastructureError` — shared catch-all (`core/`), opaques repository /
 * cross-BC asset-service infrastructure failures.
 * 
 * `OpenHoldingError` itself owns no variants; it only enumerates which
 * leaves the open_holding command can produce.
 */
export type OpenHoldingError = 
/**
 * Service-layer rejection (`AccountNotFound`).
 */
AccountApplicationError | 
/**
 * Use-case-layer rejection (cross-BC asset checks).
 */
OpenHoldingApplicationError | 
/**
 * Aggregate-level domain rejection (`InvalidTotalCost`).
 */
OpeningBalanceDomainError | 
/**
 * Transaction-factory validation rejection (invalid date, negative
 * quantity, etc. — subset of variants reachable from `open_holding`).
 */
TransactionDomainError | 
/**
 * Opaque catch-all for repository / cross-BC asset-service failures.
 * Wire shape: `{ code: "Unknown", hint: "..." }`. The `hint` mirrors the
 * corresponding `tracing::error!` log; FE shows `error.Unknown`.
 */
InfrastructureError
/**
 * Aggregate-level domain rejection raised by `Account::open_holding` on its
 * own input — currently only the `total_cost > 0` invariant (TRX-045).
 */
export type OpeningBalanceDomainError = 
/**
 * total_cost was zero or negative (TRX-045).
 */
{ code: "InvalidTotalCost" }
/**
 * Parameters for recording a sale of an asset from an account.
 */
export type SellHoldingDTO = { 
/**
 * Account where the sale is recorded.
 */
account_id: string; 
/**
 * Financial asset being sold.
 */
asset_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Quantity in micro-units.
 */
quantity: number; 
/**
 * Unit price in asset currency (micro-units).
 */
unit_price: number; 
/**
 * Exchange rate asset→account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Fees in account currency (micro-units).
 */
fees: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * A single financial event affecting an asset's quantity and cost basis within an account.
 * All financial fields are stored as i64 micro-units (ADR-001, TRX-024).
 */
export type Transaction = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * The account where the transaction occurred.
 */
account_id: string; 
/**
 * The financial asset involved.
 */
asset_id: string; 
/**
 * Type of transaction: Purchase, Sell, or OpeningBalance.
 */
transaction_type: TransactionType; 
/**
 * Date when the transaction was executed (ISO 8601, "YYYY-MM-DD").
 */
date: string; 
/**
 * Number of units traded (micro-units: value × 10^6). Must be > 0.
 */
quantity: number; 
/**
 * Price per unit in asset's native currency (micro-units). Can be 0 (gifted assets).
 */
unit_price: number; 
/**
 * Conversion rate from asset currency to account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Transaction fees in account currency (micro-units).
 */
fees: number; 
/**
 * Total cost (Purchase) or proceeds (Sell) in account currency (micro-units). Must be > 0.
 */
total_amount: number; 
/**
 * Optional user comment.
 */
note: string | null; 
/**
 * Realized P&L for Sell transactions (micro-units, SEL-024). NULL for Purchase.
 */
realized_pnl: number | null; 
/**
 * ISO 8601 timestamp of record creation — used for same-date tie-breaking (SEL-024).
 */
created_at: string }
/**
 * Typed errors for transaction domain validation (TRX-020).
 * 
 * Derives `Serialize + specta::Type + #[serde(tag = "code")]` so it can be exposed
 * at the Tauri boundary verbatim — boundary error types compose this enum via
 * untagged unions instead of redefining its variants (PR #5 review feedback).
 */
export type TransactionDomainError = 
/**
 * Date string could not be parsed as YYYY-MM-DD.
 */
{ code: "InvalidDate" } | 
/**
 * Transaction date is in the future.
 */
{ code: "DateInFuture" } | 
/**
 * Transaction date is before 1900-01-01.
 */
{ code: "DateTooOld" } | 
/**
 * Quantity is zero or negative.
 */
{ code: "QuantityNotPositive" } | 
/**
 * Cash deposit/withdrawal amount was zero or negative (CSH-021/CSH-031).
 * Cash-specific framing of the same TRX-020 constraint that surfaces as
 * `QuantityNotPositive` for non-cash transactions; raised by the cash
 * factories (`Transaction::new_deposit` / `new_withdrawal`) BEFORE the
 * generic check, so the FE sees the cash-specific error code.
 */
{ code: "AmountNotPositive" } | 
/**
 * Unit price is negative.
 */
{ code: "UnitPriceNegative" } | 
/**
 * Fees amount is negative.
 */
{ code: "FeesNegative" } | 
/**
 * Exchange rate is zero or negative.
 */
{ code: "ExchangeRateNotPositive" } | 
/**
 * Total amount is zero or negative.
 */
{ code: "TotalAmountNotPositive" }
/**
 * Type of financial transaction.
 */
export type TransactionType = 
/**
 * A purchase (acquisition) of an asset.
 */
"Purchase" | 
/**
 * A sale of a previously purchased asset.
 */
"Sell" | 
/**
 * Seeds a holding directly from a known quantity and total cost, without full transaction history (TRX-042).
 */
"OpeningBalance" | 
/**
 * A cash inflow from outside the application's tracked world (CSH-022).
 */
"Deposit" | 
/**
 * A cash outflow to outside the application's tracked world (CSH-032).
 */
"Withdrawal"
/**
 * Parameters for updating an existing account.
 */
export type UpdateAccountDTO = { 
/**
 * Target account ID.
 */
id: string; 
/**
 * New display name.
 */
name: string; 
/**
 * ISO 4217 currency code.
 */
currency: string; 
/**
 * New update frequency.
 */
update_frequency: UpdateFrequency }
/**
 * Parameters for updating an existing asset.
 */
export type UpdateAssetDTO = { 
/**
 * Target asset ID.
 */
asset_id: string; 
/**
 * New display name.
 */
name: string; 
/**
 * New reference (mandatory — R1).
 */
reference: string; 
/**
 * New classification.
 */
class: AssetClass; 
/**
 * New currency.
 */
currency: string; 
/**
 * New risk level.
 */
risk_level: number; 
/**
 * New category link.
 */
category_id: string }
/**
 * Defines how often an account's data should be updated.
 */
export type UpdateFrequency = 
/**
 * Automatic updates (e.g. via API)
 */
"Automatic" | 
/**
 * Manual update daily
 */
"ManualDay" | 
/**
 * Manual update weekly
 */
"ManualWeek" | 
/**
 * Manual update monthly
 */
"ManualMonth" | 
/**
 * Manual update yearly
 */
"ManualYear"
/**
 * Information about an available application update.
 */
export type UpdateInfo = { 
/**
 * Semantic version string of the available update (e.g. "1.2.3").
 */
version: string }
/**
 * Application-layer errors raised by the asset web-lookup use case.
 * 
 * Single variant — covers all failure modes: network unreachable, connection
 * timeout, and any non-2xx HTTP status (including rate-limiting responses)
 * from the OpenFIGI client (WEB-025).
 */
export type WebLookupApplicationError = 
/**
 * All network or HTTP-level failures.
 */
{ code: "NetworkError" }
/**
 * Parameters for recording a cash withdrawal (CSH-030).
 */
export type WithdrawalDTO = { 
/**
 * Account from which to withdraw cash.
 */
account_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Withdrawn amount in account currency (micro-units); strictly positive (CSH-031).
 */
amount_micros: number; 
/**
 * Optional user note.
 */
note: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
